export const PRODUCT = "product";
export const CATEGORY = "category";
export const CARD = "card";
export const ORDER = "order";
export const ADMIN = "admin";
export const COMMENT = "comment";

export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";
export const GET_ALL_PRODUCTS_ERROR = "GET_ALL_PRODUCTS_ERROR";
export const GET_PRODUCT = "GET_PRODUCT";
export const ADD_PRODUCT = "ADD_PRODUCT";
export const ADD_PRODUCT_ERROR = "ADD_PRODUCT_ERROR";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const UPDATE_PRODUCT_COMMENT = "ADD_PRODUCT_COMMENT";
export const UPDATE_PRODUCT_COMMENT_ERROR = "UPDATE_PRODUCT_COMMENT_ERROR";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const DELETE_PRODUCT_ERROR = "DELETE_PRODUCT_ERROR";
export const CHANGE_FILTER = "CHANGE_FILTER";
export const SEARCH_PRODUCT_NAME = "SEARCH_FILTER_NAME";

export const GET_CATEGORY = "GET_CATEGORY";
export const GET_CATEGORY_ERROR = "GET_CATEGORY_ERROR";

export const GET_ALL_CARD = "GET_CARD";
export const GET_ALL_CARD_ERROR = "GET_CARD_ERROR";
export const ADD_CARD = "ADD_CARD";
export const ADD_CARD_ERROR = "ADD_CARD_ERROR";
export const DELETE_CARD = "DELETE_CARD";
export const DELETE_CARD_ERROR = "DELETE_CARD_ERROR";
export const UPDATE_CARD_QUANTITY = "UPDATE_CARD_QUANTITY";
export const UPDATE_CARD_QUANTITY_ERROR = "UPDATE_CARD_QUANTITY_ERROR";
export const INCREMENT_QUANTITY_CARD = "INCREMENT_QUANTITY_CARD";
export const INCREMENT_QUANTITY_CARD_ERROR = "INCREMENT_QUANTITY_CARD_ERROR";
export const DESCREMENT_QUANTITY_CARD = "DESCREMENT_QUANTITY_CARD";
export const DESCREMENT_QUANTITY_CARD_ERROR = "DESCREMENT_QUANTITY_CARD_ERROR";

export const ADD_ORDER = "ADD_ORDER";
export const ADD_ORDER_ERROR = "ADD_ORDER_ERROR";
export const CHANGE_PURCHASE = "CHANGE_PURCHASE";
export const CHANGE_PURCHASE_ERROR = "CHANGE_PURCHASE_ERROR";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";
